# Config file for automatic testing at travis-ci.org

sudo: false
language: python
matrix:
  fast_finish: true
  include:
    - python: "2.7"
    - python: "3.5"

install:
    - pip install -e .[test]
    - pip install codecov

script:
    - cd bincrafters/test
    - pytest -v --cov=bincrafters

after_success:
    - codecov

deploy:
  provider: pypi
  user: "uilianries"
  password:
    secure:  "CYNbUPCuSaXNzMkxXLzHpzE77eGkooU+0eb3OG4ydyh0IRKBmHBqc0bHc6J1UwhzzeFoQ2eOSuRSHiVLwRZEZEiTIh+NORjfvNpPnbH6YN9nGKwFH7JndbVAd8+NWyb2QjtYocepHOGAhR1ILeAWtivCpIb9iBqQbKy9PwlsuUkdqxR7VV41pYIOOFAGmrqw9/+Q/ujhXtq2QKHqLvLgkE93GujJy+EKdH2leon9AUXWJ3GGQaCF35J+eD4udpWfk6RteYqN8moZWkASoAsZNdsblHQqLYgREn4366D+t6DMOiYpz9nszmRn7Ct2yUgmFQ82BomaaCLAaczXJaOTOYO9ixgHDz2EG6Hr7P1mr+VnPxnudGQac6iQjakel2qNpvTDOfKbECuOtwA9PNdxy0j9LsH4SHi0fbAWKx7yc+uNh1ckzP5Q4gBJ7kdgdZFfopCpBpMNt1gdae1wO9TPf6UW28lUS0Ei0NIQBJ7Bv+sIDhTRojfILaELu0B2cFSwv3fhxny6AydTTfHppHrErPJ7oaYPBlx3g2SESSuhHarH66QA0bFIIO/mVln4JHnnposeRU0Ps9ajPNJKjjoNSoOc+itIQ3xFgIYE8C4fysLrd64DfdS8C0oISPBby/zEQZJzgtgM65bfE4kZJz/8j0AovKnYAgjI166SP/+sa1o="
