sudo: false
language: python

matrix:
  fast_finish: true
  include:
    - python: '2.7'
    - python: '3.5'

install:
  - pip install -e .[test]
  - pip install codecov

script:
  - cd bincrafters/test
  - pytest -v --cov=bincrafters

after_success:
  - codecov
  - cd -

deploy:
  provider: pypi
  user: uilianries
  password:
    secure: "tXFUd519XiwEX9nTCByxZn4VvGVBRSQDbznM8OUPuKWh+w4WNeTPxKDaSsyrywwit+Cx9HXhPcYriOSTfZCLuVtlHesdKkKvvvoXLotOBGKbF4Nky9P4kkB3q6bG4ltnTW4Hmik7WDCWmOB1mp6IwCuzJt8sShvQHJDJdZKF+EYaZP72zdFVYwL+PVhxuqzZpnP+zn6iPrc9tKO6RNrJwNHLpIk5gIEoK3kfGyhrfuvmTTeYjwS2EiuPOmhPV7ZuvhFZxAJr6YkBaWFcvU1p+Mnh1vO9KgyTmv2DN5dVXCTwJ55lu+kiiF4EDltUjrjg4LtdFFUKAvkb1Qydog8O6A5pxuLUfgKXYIssz68K5td3eULEWUi1haRwrPzX8VIm9wIGW23nKyj8z2dX/ro7Lm6KXIWbjP5Twac1zcr7/JH4uxUnsYDTBpkLHomAxTZ4N9L1DDaTfIiV5SFaMK/zxYPFSoNrA/ooL13f2ojNeF3CDgG/cTI0tdvhvJr0+bIdDuP4VeTetTwE6SDEC3usJ2UYcapsnnoZHveHWZx5oOUF8gdG+mkpS0wYPeCZfbxyNaqQ9yqhxZJWEag5W7gT9hbLYRXRSPTmiZnvFmXuU6wRF5S+IVZMV06eX0S4RpCMWwW/EgpFbSC8tz4jlnAJ3nlxyamJFSvy6fjeIvpYFUk="
