sudo: false
language: python

matrix:
  fast_finish: true
  include:
    - python: '2.7'
    - python: '3.5'

install:
  - pip install -e .[test]
  - pip install codecov

script:
  - cd bincrafters/test
  - pytest -v --cov=bincrafters
  - cd -

after_success:
  - codecov

deploy:
  provider: pypi
  user: uilianries
  password:
    secure: MpvcbCCDqW8LRmnKeIIwa+VbM7Fiy2M/wzJgXAVyd3xn4l6Zk8dFjhR1S/jpsriGp/hsnE4+dvCeWYSp+naILKVAGCD0/yzA5lIfyKN3a8myCY52VwQLkCFICZ9Y2SaKKl57QMDLMWPInnd9dDFVToZcVkH8kXlnVKIRXyeMVNViMTkEUHuBUDQD3ICNJidIU3Wgf95bIb+yI0bzna/YQlC2InV0l4rdCr29x7JenjxX0h7sMkbXkYf8NA7MUAswbTrvRcv4AZeynmKVlYEVttMnY/bp00TM/RwVEIXG20+a6MDbbJH1lc3wvYbbIuZ8HFnm7XS0DLT7feXhw9+Vk1GN+t+BoL7yhxoAQBMYCneXrWWpf9z8+g1inTKNkOhK76OGJ9L1CX4wnDRuSh+PJcx8emnSw46XuNLt9uRobdG7Zz95LktfSMPdDonYoalsM4eIZXQsacGGi4u5DWYuwLMIeCk2tIyTV1XK1chF9Es9fEAEZn0aV9kEAOLE0EHLaYfBIbDuHqmD99TE/KkW6xUpT5qk+WbwzNw+1GM6oOi2WPHXiVpukCiRNAGtii2XYwurRTsVJXXwXdHBSpZ4s9mHY4yNo6+VYPERJ2BZuGb2dAv9v9zaB8fb1B0IqPkfkZdZsnTwLXHo2D+HEvWg/fDSNJ+ty35gLclM3l0hZ2k=
