environment:
  PYTHON_HOME: "C:\\Python37"

  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip install -e .[test]

build_script:
  - cd tests
  - pytest -v --cov=bincrafters
