on: [push, pull_request]

name: "bincrafters-package-tools"

jobs:
  bincrafters-package-tools-test:
    name: Test Tools on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    if: github.event_name == 'push'
    strategy:
      fail-fast: false
      matrix:
        #os: ["ubuntu-20.04", "windows-2019", "macos-10.15"]
        os: ["windows-2019"]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: "Build & Test"
      run: |
        pip install -e .[test]
        python setup.py sdist
        cd tests
        pytest -v -s --cov=bincrafters
        mv .coverage ..
        cd ..
        codecov
